version: "3.8"

services:
  db:
    container_name: postgres_container
    image: postgres:15
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: keypro
      PGDATA: /data/postgres
    volumes:
      - postgres:/data/postgres
    ports:
      - "5439:5432"
    restart: unless-stopped

volumes:
  postgres:
